openapi: "3.1.0"
info:
  title: "roomie API"
  description: "roomie API"
  version: "1.0.0"
servers:
- url: "http://0.0.0.0:8080"
paths:
  /registration/additional-data:
    post:
      description: ""
      requestBody:
        content:
          '*/*':
            schema:
              $ref: "#/components/schemas/AdditionalInfoRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "User additional data updated successfully"
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Failed to update user additional data"
  /registration/available-departments:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Map_Faculty"
  /registration/available-hobbies:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  type: "string"
                  enum:
                  - "basketball"
                  - "football"
                  - "volleyball"
                  - "swimming"
                  - "running"
                  - "cycling"
                  - "hiking"
                  - "climbing"
                  - "skiing"
                  - "music"
                  - "dance"
                  - "cooking"
                  - "painting"
                  - "photography"
  /auth/login:
    post:
      description: ""
      requestBody:
        content:
          '*/*':
            schema:
              $ref: "#/components/schemas/LoginRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AuthResponse"
        "401":
          description: "Unauthorized"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Invalid credentials"
  /auth/logout:
    post:
      description: ""
      parameters:
      - name: "Authorization"
        in: "header"
        required: false
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Logged out successfully"
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Invalid token"
  /auth/register:
    post:
      description: ""
      requestBody:
        content:
          '*/*':
            schema:
              $ref: "#/components/schemas/RegisterRequest"
        required: true
      responses:
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AuthResponse"
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: ""
components:
  schemas:
    Info:
      type: "object"
      properties:
        age:
          type: "integer"
          format: "int32"
        description:
          type: "string"
        sleepSchedule:
          type: "integer"
          format: "int32"
        hobbies:
          type: "array"
          items:
            type: "string"
            enum:
            - "basketball"
            - "football"
            - "volleyball"
            - "swimming"
            - "running"
            - "cycling"
            - "hiking"
            - "climbing"
            - "skiing"
            - "music"
            - "dance"
            - "cooking"
            - "painting"
            - "photography"
        smoke:
          type: "boolean"
        drink:
          type: "boolean"
        personalityType:
          type: "integer"
          format: "int32"
        yearOfStudy:
          type: "integer"
          format: "int32"
        faculty:
          type: "string"
          enum:
          - "WILiGZ"
          - "WIMiIP"
          - "WEAIIB"
          - "WIET"
          - "WIMiR"
          - "WGGiOS"
          - "WGGiIS"
          - "WIMiC"
          - "WO"
          - "WMN"
          - "WWNiG"
          - "WZ"
          - "WEiP"
          - "WFiIS"
          - "WMS"
          - "WH"
          - "WI"
          - "WTK"
        relationshipStatus:
          type: "integer"
          format: "int32"
      required:
      - "age"
      - "description"
      - "sleepSchedule"
      - "hobbies"
      - "smoke"
      - "drink"
      - "personalityType"
      - "yearOfStudy"
      - "faculty"
      - "relationshipStatus"
    Preferences:
      type: "object"
      properties:
        sleepScheduleMatters:
          type: "boolean"
        hobbiesMatters:
          type: "boolean"
        smokingImportance:
          type: "integer"
          format: "int32"
        drinkImportance:
          type: "integer"
          format: "int32"
        personalityTypeImportance:
          type: "integer"
          format: "int32"
        yearOfStudyMatters:
          type: "boolean"
        facultyMatters:
          type: "boolean"
        relationshipStatusImportance:
          type: "integer"
          format: "int32"
      required:
      - "sleepScheduleMatters"
      - "hobbiesMatters"
      - "smokingImportance"
      - "drinkImportance"
      - "personalityTypeImportance"
      - "yearOfStudyMatters"
      - "facultyMatters"
      - "relationshipStatusImportance"
    AdditionalInfoRequest:
      type: "object"
      properties:
        userId:
          type: "integer"
          format: "int32"
        info:
          $ref: "#/components/schemas/Info"
        preferences:
          $ref: "#/components/schemas/Preferences"
      required:
      - "userId"
      - "info"
      - "preferences"
    Map:
      type: "object"
      properties: {}
    Map_Faculty:
      type: "string"
    LoginRequest:
      type: "object"
      properties:
        email:
          type: "string"
        password:
          type: "string"
      required:
      - "email"
      - "password"
    AuthResponse:
      type: "object"
      properties:
        token:
          type: "string"
        userId:
          type: "integer"
          format: "int32"
      required:
      - "token"
      - "userId"
    RegisterRequest:
      type: "object"
      properties:
        email:
          type: "string"
        password:
          type: "string"
      required:
      - "email"
      - "password"