services:
  - type: web
    name: roomie-backend
    env: docker
    plan: free
    buildCommand: ./gradlew run

  - type: web
    name: roomie-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 80
    buildCommand: npm install && npm run build
