services:
  - type: web
    name: roomie-backend
    env: docker
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8080

  - type: web
    name: roomie-frontend
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 80
    buildCommand: npm install
    runCommand: npm start
