services:
  - type: web
    name: roomie-backend
    runtime: docker
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8080
      - key: DEPLOYMENT
        value: "true"

  - type: web
    name: roomie-frontend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist -l 80
    rootDir: frontend
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 80
      - key: VITE_BACKEND_URL
        value: https://roomie-backend-wnzd.onrender.com
